### ISSUE TITLE
PROPKA gives uninterpretable error

### ISSUE THREAD

**Issue by sobolevnrm** [jensengroup/propka#118]
Running PROPKA on 1HCH gives the following error:
```
Traceback (most recent call last):
  File "opt/anaconda3/envs/propka/bin/propka3", line 33, in <module>
    sys.exit(load_entry_point('propka', 'console_scripts', 'propka3')())
  File "propka/propka/run.py", line 42, in main
    my_molecule = read_molecule_file(pdbfile, my_molecule)
  File "propka/propka/input.py", line 113, in read_molecule_file
    mol_container.extract_groups()
  File "propka/propka/molecular_container.py", line 81, in extract_groups
    self.conformations[name].extract_groups()
  File "propka/propka/conformation_container.py", line 70, in extract_groups
    self.setup_and_add_group(group)
  File "propka/propka/conformation_container.py", line 165, in setup_and_add_group
    self.init_group(group)
  File "propka/propka/conformation_container.py", line 176, in init_group
    group.setup()
  File "propka/propka/group.py", line 321, in setup
    self.setup_atoms()
  File "propka/propka/group.py", line 744, in setup_atoms
    PROTONATOR.protonate_atom(the_nitrogen[0])
IndexError: list index out of range
```

**Comment by sobolevnrm** [comment]
Fixed by #114
