### ISSUE TITLE
Error in construction of a network of hydrogen bonds 

### ISSUE THREAD

**Issue by boristim66** [jensengroup/propka#128]
The construction of a network of hydrogen bonds does not work for atoms of the same residues with the same numbers, but belonging to different chains due sort error :
[3hto_chainsOB.zip](https://github.com/jensengroup/propka/files/6678834/3hto_chainsOB.zip)
$ pdb2pqr30  --ff AMBER --with-ph 4.5 --drop-water --keep-chain "3hto_chainsOB.pdb"  "3hto_chainsOB.pqr"
............
DEBUG:* Optimizeable to optimizeable *
DEBUG:* Water to Water *
DEBUG:Starting network ASN B 595 (Flip), ASN D 595 (Flip), ASN F 595 (Flip)
DEBUG:* Optimizeable to backbone *
Traceback (most recent call last):
  File "/usr/local/bin/pdb2pqr30", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pdb2pqr/main.py", line 796, in main
    main_driver(args)
  File "/usr/local/lib/python3.7/dist-packages/pdb2pqr/main.py", line 765, in main_driver
    is_cif=is_cif,
  File "/usr/local/lib/python3.7/dist-packages/pdb2pqr/main.py", line 641, in non_trivial
    hydrogen_routines.optimize_hydrogens()
  File "/usr/local/lib/python3.7/dist-packages/pdb2pqr/hydrogens/__init__.py", line 485, in optimize_hydrogens
    hbondlist = util.sort_dict_by_value(hbondmap)
  File "/usr/local/lib/python3.7/dist-packages/pdb2pqr/utilities.py", line 33, in sort_dict_by_value
    items.sort()
TypeError: '<' not supported between instances of 'PotentialBond' and 'PotentialBond'

**Comment by boristim66** [comment]
This is a bug of  pdb2pqr, sorry
