### ISSUE TITLE
Problem with running Propka3

### ISSUE THREAD

**Issue by AhmedEzat** [jensengroup/propka#129]
Dear Sir,

I am not sure if the issue had been raisen before but I get this error while trying to run propka3

Traceback (most recent call last):
  File "e:\anaconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\Scripts\propka3.exe\__main__.py", line 7, in <module>
  File "e:\anaconda\lib\site-packages\propka\run.py", line 42, in main
    my_molecule = read_molecule_file(pdbfile, my_molecule)
  File "e:\anaconda\lib\site-packages\propka\input.py", line 98, in read_molecule_file
    conformations, conformation_names = read_pdb(
  File "e:\anaconda\lib\site-packages\propka\input.py", line 237, in read_pdb
    for (name, atom) in lines:
  File "e:\anaconda\lib\site-packages\propka\input.py", line 173, in get_atom_lines_from_pdb
    model = int(line[6:])
ValueError: invalid literal for int() with base 10: ' \n'

**Comment by sobolevnrm** [comment]
Can you please provide more information?

* What OS and version of Python are you using?
* What version of PROPKA are you using?
* Can you provide a copy of the PDB file that causes the error?

Thank you

**Comment by AhmedEzat** [comment]
Is there any solution to my problem?

Many thanks in advance for your efforts.

**Comment by sobolevnrm** [comment]
Not yet, sorry.

**Comment by sobolevnrm** [comment]
Hello.  Your PDB file appears to be missing an integer for the "MODEL" statement which is required by the standard:  https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#MODEL
