### ISSUE TITLE
PROPKA fails with "AttributeError: 'NoneType' object has no attribute 'group_type'"

### ISSUE THREAD

**Issue by sobolevnrm** [jensengroup/propka#140]
This was originally reported in https://github.com/Electrostatics/pdb2pqr/issues/302 but is a PROPKA issue rather than a PDB2PQR issue.

Running PROPKA 3.4.0 on the attached structure with
```
propka3 protein.pdb
```
gives the error
```
Traceback (most recent call last):
  File "/home/baker/venv/pdb2pqr/bin/propka3", line 8, in <module>
    sys.exit(main())
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/run.py", line 43, in main
    my_molecule.calculate_pka()
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/molecular_container.py", line 87, in calculate_pka
    self.conformations[name].calculate_pka(
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/conformation_container.py", line 208, in calculate_pka
    set_determinants(
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/determinants.py", line 60, in set_determinants
    add_determinants(group1, group2, distance, version)
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/determinants.py", line 75, in add_determinants
    add_sidechain_determinants(group1, group2, version)
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/determinants.py", line 90, in add_sidechain_determinants
    hbond_interaction = version.hydrogen_bond_interaction(group1, group2)
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/version.py", line 61, in hydrogen_bond_interaction
    return self.hydrogen_bond_interaction_model(group1, group2, self)
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/energy.py", line 261, in hydrogen_bond_interaction
    exception, value = version.check_exceptions(group1, group2)
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/version.py", line 91, in check_exceptions
    return self.exception_check_method(self, group1, group2)
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/energy.py", line 394, in check_exceptions
    exception, value = check_coo_arg_exception(group1, group2, version)
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/energy.py", line 443, in check_coo_arg_exception
    [dpka_max, cutoff] = version.get_hydrogen_bond_parameters(
  File "/home/baker/venv/pdb2pqr/lib/python3.8/site-packages/propka/version.py", line 133, in get_hydrogen_bond_parameters
    atom1.group_type, atom2.group_type)
AttributeError: 'NoneType' object has no attribute 'group_type'
```

[protein.zip](https://github.com/jensengroup/propka/files/8103363/protein.zip)

**Comment by speleo3** [comment]
Fixed in https://github.com/jensengroup/propka/pull/169
