### ISSUE TITLE
Exception thrown when alternate location indicator is not 1, A or whitespace

### ISSUE THREAD

**Issue by stcmz** [jensengroup/propka#20]
Traceback (most recent call last):
  File "/home/ryan/.local/bin/propka31", line 11, in <module>
    load_entry_point('PROPKA==3.1.0', 'console_scripts', 'propka31')()
  File "/home/ryan/.local/lib/python3.6/site-packages/PROPKA-3.1.0-py3.6.egg/propka/run.py", line 13, in main
  File "/home/ryan/.local/lib/python3.6/site-packages/PROPKA-3.1.0-py3.6.egg/propka/molecular_container.py", line 46, in __init__
  File "/home/ryan/.local/lib/python3.6/site-packages/PROPKA-3.1.0-py3.6.egg/propka/molecular_container.py", line 88, in top_up_conformations
KeyError: '1A'

**Comment by sobolevnrm** [comment]
Do you have a specific PDB we can use to troubleshoot this issue?

**Comment by speleo3** [comment]
I do get a warning, but no error.

[example-pdb.txt](https://github.com/jensengroup/propka/files/5651533/example-pdb.txt)

**Comment by speleo3** [comment]
Duplicate of https://github.com/jensengroup/propka/issues/147
