### ISSUE TITLE
PROPKA==3.1.0' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by sacak1** [jensengroup/propka#24]
Hello,

I just installed propka 3.1 (I never worked with gnu-linux before) and I get this message when I try to run the propka command with a pdb argument  

samuel@samuel-UX305CA:~$ propka31 '/home/samuel/Downloads/2jfz_monom_reFH.pdb'
Traceback (most recent call last):
File "/usr/local/bin/propka31", line 6, in <module>
from pkg_resources import load_entry_point
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
@_call_aside
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
f(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
ws.require(__requires__)
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 892, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PROPKA==3.1.0' distribution was not found and is required by the application

Do you know what could I do to make this work ?

Thanks 

Sam

**Comment by orbeckst** [comment]
You probably need to install the package, see [INSTALL](https://github.com/jensengroup/propka-3.1/blob/master/INSTALL) for installation from source or just
```
pip install PROPKA
```
might also work as there is a [PROPKA package on PyPi](https://pypi.org/project/PROPKA/).

**Comment by orbeckst** [comment]
@sacak1 did you manage to get propka installed?

Without further feedback we will close this issue.

**Comment by orbeckst** [comment]
propka is now regularly released on https://pypi.org/project/propka/
